### ISSUE TITLE
Add Discontinued/Abandoned Projects?

### ISSUE THREAD

**Issue by meichthys** [mattrob33/christian-projects#13]
Do we want to add discontinued or archived/discontinued/abandoned projects? It seems like there may still be value even if we don't want to list them in the normal list.

Perhaps we can add a new category solely for archived/discontinued/abandoned apps?

**Comment by meichthys** [comment]
Some apps that would fall into this category:

- https://github.com/monty5811/apostello/
- https://github.com/cedarsuite/cedarserver
- http://sourceforge.net/projects/churchinfo
- https://github.com/seven1m/onebody
- https://sourceforge.net/projects/softprojector/

**Comment by mattrob33** [comment]
Great question, thanks for raising it as an issue. I agree that there could still be value in them. It might be helpful to mark them in some way though, like placing an asterisk beside the name, with a note that projects marked with an asterisk have been discontinued. Like this

> *Projects marked with an asterisk (*) have been archived or abandoned.
> 
> Apostello* | ...
> CedarServer* | ...

What do you think?

**Comment by meichthys** [comment]
Seems reasonable to me 👍
It would be nice if we could automate this somewhat by fetching the last commit date for each project and display that somehow. We can save that for another time though.

**Comment by mattrob33** [comment]
> It would be nice if we could automate this somewhat by fetching the last commit date for each project and display that somehow.

Interesting idea. I wonder if we could do this with badges, like how CircleCI, Bitrise, etc, use badges to show the current build status of a project. I'll create a new issue for this with a help wanted tag.

**Comment by meichthys** [comment]
Closing this issue for now. We can create new issues later on if we need to modify the way we track archived repos.
