### ISSUE TITLE
List of software/project which has import/search with highlights of sermon add and search ?

### ISSUE THREAD

**Issue by passionate2023** [mattrob33/christian-projects#37]
Hi,

Can you please add the list of software/project which allows sermons add i.e import of sermons in text file (.txt) and doc files (.doc/.docx) and have search with highlights?

Thanks

**Comment by passionate2023** [comment]
the simplenote works awesome for import text and search. However we cannot categorize as 
1. sermons
2. bible
also the structure and navigation with specific would be very hard.....

looking for one web application, one desktop application which has the following features

1. Import of bible, sermons, dictionaries, songs - txt
2. Highlight the given keyword by specific any specific heading or folder name or nodes heading
3. Easy navigation of search results for given keyword in each file or each content with arrows < > ^
4. Public sharing URL of entire collection with search to the end user where user cannot edit or delete the content

Just see how beautifully the english bible web app is designed...few for reference

https://english-bible.el-elupath-elu.in/
https://raw.githubusercontent.com/wiki/zadam/trilium/images/screenshot.png

**Comment by mattrob33** [comment]
Closing this issue as off-topic since it seems to be a request for recommendations rather than a suggestion for this repo.
